export const title: string;
export const tabPanelContainer: string;
export const tabPanel: string;
export const prevEnterActive: string;
export const prevExitActive: string;
export const nextEnterActive: string;
export const nextExitActive: string;
export const prevEnter: string;
export const nextEnter: string;
